version: '3.8'
services:
  noticat:
    image: ghcr.io/speechlessmatt/noticat-server:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NOTICAT_JWT_SECRET=your_jwt_secret
      - NOTICAT_SMTP_SERVER=qq
      - NOTICAT_EMAIL_ACCOUNT=boss@example.com
      - NOTICAT_EMAIL_AUTHCODE=your_smtp_auth

      - REDIS_ADDR=redis:6379 
    depends_on:
      - redis
    # volumes:
    #   - ./scripts:/app/scripts:ro

  redis:
    image: redis:7-alpine
    restart: unless-stopped